export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRM_BOOKING = 'CONFIRM_BOOKING',
  CONFIRMED_PAYMENT = 'CONFIRMED_PAYMENT',
  CHECKED_IN = 'CHECKED_IN',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  DELAY = 'DELAY',
}
