export enum EmailJobNameEnum {
  SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION',
  SEND_EMAIL_WELCOME_STAFF = 'SEND_EMAIL_WELCOME_STAFF',
  SEND_EMAIL_BOOKING_SUCCESS = 'SEND_EMAIL_BOOKING_SUCCESS',
}
